name = "louie-sawyer-portfolio"
compatibility_date = "2024-01-01"

[env.production]
name = "louie-sawyer-portfolio"

[env.development]
name = "louie-sawyer-portfolio-dev"

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"

# KV namespaces for data storage (if needed)
# [[kv_namespaces]]
# binding = "PORTFOLIO_KV"
# id = "your-kv-namespace-id"

# D1 database binding (if needed)
# [[d1_databases]]
# binding = "PORTFOLIO_DB"
# database_name = "portfolio-database"
# database_id = "your-database-id"

# Assets configuration
[site]
bucket = "./frontend/build"

# Worker script configuration
main = "./worker/index.js"

# Routes configuration - Supporting Louie's domains
routes = [
  { pattern = "louie.sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },
  { pattern = "louie.sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" },
  { pattern = "sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },
  { pattern = "sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" }
]

# Build configuration
[build]
command = "yarn build"
cwd = "./frontend"

# TypeScript support
[build.upload]
format = "modules"