name = "louie-sawyer-portfolio"
compatibility_date = "2024-01-01" 
main = "./worker/index-simple.js"

# Skip workers.dev entirely - only use custom domains
workers_dev = false

# Routes for custom domains
routes = [
  { pattern = "louie.sawyers-enterprises.co.uk/*", zone_name = "sawyers-enterprises.co.uk" },
  { pattern = "louie.sawyers-enterprises.uk/*", zone_name = "sawyers-enterprises.uk" },
  { pattern = "sawyers-enterprises.co.uk/*", zone_name = "sawyers-enterprises.co.uk" },
  { pattern = "sawyers-enterprises.uk/*", zone_name = "sawyers-enterprises.uk" }
]

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"
RESEND_API_KEY = ""

# Workers Sites configuration - this will automatically create and bind __STATIC_CONTENT KV namespace on deployment
[site]
bucket = "./frontend/build"