name = "louie-sawyer-portfolio"
compatibility_date = "2024-01-01" 
main = "./worker/index-simple.js"

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"

# Static assets configuration for Workers Sites
[site]
bucket = "./frontend/build"

# Enable workers.dev subdomain deployment
workers_dev = true

# Routes configuration - Supporting Louie's domains (add these later after domains are configured)
# routes = [
#   { pattern = "louie.sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },
#   { pattern = "louie.sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" },
#   { pattern = "sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },  
#   { pattern = "sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" }
# ]

# KV namespaces for data storage (if needed)
# [[kv_namespaces]]
# binding = "PORTFOLIO_KV"
# id = "your-kv-namespace-id"

# D1 database binding (if needed)
# [[d1_databases]]
# binding = "PORTFOLIO_DB"
# database_name = "portfolio-database"
# database_id = "your-database-id"