name = "louie-sawyer-portfolio"
compatibility_date = "2024-01-01" 
main = "./worker/index-simple.js"

# Skip workers.dev entirely - only use custom domains
workers_dev = false

# Routes for custom domains - TOP LEVEL
# Primary subdomain routes for louie.domain format
routes = [
  { pattern = "louie.sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },
  { pattern = "louie.sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" },
  # Optional: Handle root domain redirects to subdomain
  { pattern = "sawyer-enterprises.co.uk/*", zone_name = "sawyer-enterprises.co.uk" },
  { pattern = "sawyer-enterprises.uk/*", zone_name = "sawyer-enterprises.uk" }
]

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"

# Modern static assets configuration
assets = { directory = "./frontend/build" }

# KV namespaces for data storage (if needed)
# [[kv_namespaces]]
# binding = "PORTFOLIO_KV"
# id = "your-kv-namespace-id"

# D1 database binding (if needed)
# [[d1_databases]]
# binding = "PORTFOLIO_DB"
# database_name = "portfolio-database"
# database_id = "your-database-id"