name = "louie-sawyer-portfolio"
compatibility_date = "2024-01-01" 
main = "./worker/index-simple.js"

# Skip workers.dev entirely - only use custom domains
workers_dev = false

# Routes for custom domains
routes = [
  { pattern = "louie.sawyers-enterprises.co.uk/*", zone_name = "sawyers-enterprises.co.uk" },
  { pattern = "louie.sawyers-enterprises.uk/*", zone_name = "sawyers-enterprises.uk" },
  { pattern = "sawyers-enterprises.co.uk/*", zone_name = "sawyers-enterprises.co.uk" },
  { pattern = "sawyers-enterprises.uk/*", zone_name = "sawyers-enterprises.uk" }
]

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"

# Workers Sites configuration
[site]
bucket = "./frontend/build"

# Explicit KV namespace binding - using the actual namespace from your dashboard
[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "8f88e14f829c4cca84dcd374a1311e"
preview_id = "8f88e14f829c4cca84dcd374a1311e"