name: Deploy Full-Stack to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Full-Stack App to Cloudflare Workers
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          
      # Install root dependencies (including wrangler)
      - name: Install Wrangler CLI
        run: |
          npm install -g wrangler@latest
          
      # Verify wrangler installation
      - name: Verify Wrangler
        run: |
          wrangler --version
          
      # Build React frontend
      - name: Build frontend
        run: |
          cd frontend
          yarn install --frozen-lockfile
          yarn build
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          
      # Verify build output
      - name: Verify build output
        run: |
          ls -la frontend/build/
          echo "Build contents:"
          find frontend/build -type f | head -10
          
      # Deploy to Cloudflare Workers with custom domains
      - name: Deploy Worker to Custom Domains
        run: |
          # Deploy with custom routes - no workers.dev needed
          wrangler deploy --compatibility-date 2024-01-01
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Deployment Success
        run: |
          echo "🎉 WORKER DEPLOYED SUCCESSFULLY!"
          echo "🌐 Portfolio should be live at:"
          echo "   - https://louie.sawyer-enterprises.co.uk"
          echo "   - https://louie.sawyer-enterprises.uk"
          echo ""
          echo "📋 If domains aren't working:"
          echo "   1. Add domains to Cloudflare as zones"
          echo "   2. Update nameservers at registrar"
          echo "   3. Wait for DNS propagation"
          
      - name: Comment deployment status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Full-Stack Deployment Complete!** Frontend and backend deployed to Cloudflare Workers.'
            })