name: Deploy to Cloudflare Pages (Alternative)

# Alternative deployment method using Wrangler CLI
# Use this if the cloudflare/pages-action@v1 fails with authentication errors

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '20'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
          
      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile
          
      - name: Build application
        run: |
          cd frontend
          yarn build
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          
      - name: Deploy to Cloudflare Pages via Wrangler
        run: |
          cd frontend
          npx wrangler pages deploy build --project-name=louie-sawyer-portfolio --compatibility-date=2024-01-01
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Comment deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Deployment Complete!** Your changes have been deployed to Cloudflare Pages.'
            })