name: Deploy Full-Stack to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Full-Stack App to Cloudflare Workers
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
          
      # Install root dependencies (including wrangler)
      - name: Install root dependencies
        run: |
          yarn install --frozen-lockfile
          
      # Build React frontend
      - name: Build frontend
        run: |
          cd frontend
          yarn install --frozen-lockfile
          yarn build
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          
      # Deploy to Cloudflare Workers using Wrangler
      - name: Deploy to Cloudflare Workers
        run: |
          npx wrangler deploy --config wrangler.toml
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
      - name: Comment deployment status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 **Full-Stack Deployment Complete!** Frontend and backend deployed to Cloudflare Workers.'
            })